### PR TITLE
Use hicv as a library for html->hiccup convert

### PR DESCRIPTION
**Pull request by myguidingstar-zz**

### CODE REVIEW

**Comment by hozumi** [comment]
Hi myguidingstar,

Your changes are very nice and name convention is more idiomatic than mine.
I will merge these commits, but one point I noticed is that there are three different names that represent this project: hiccup-bridge(at github), to-hiccup(namespace) and hicv(lein command and name of the project in project.clj).
This can be confusing.
My proposal is following:
- The project name and namespace is **hiccup-bridge**
- Only lein command name is **hicv**.

What do you think?

**Comment by myguidingstar-zz** [comment]
Yes, I think that makes sense. Please go ahead

**Comment by myguidingstar-zz** [comment]
All done. I have also pushed to clojars and added you to `hiccup-bridge` group.

**Comment by hozumi** [comment]
Merged.
Thank you for your efforts!

**Pull request merged**
